#!/bin/bash

#File generated on 10.07.2023 by Cian Kelly (email:cianrkelly23@gmail.com)

#Description:
#A script that is used to initialize simulation settings using text replacements 

#I should put this and the job script text editing in another bash script- create a general init_script that controls the job time
initfile=$HOME/f90/krill_ibm/init_set.txt
trackfile=$HOME/f90/krill_ibm/krill.f90
file=$HOME/f90/sinmod/simSettings.txt

f1=$(sed -n 1p $initfile) #Sets the variable equal to the standard output.
f2=$(sed -n 2p $initfile)
tx=$(sed -n 3p $initfile)
ty=$(sed -n 4p $initfile)
tz=$(sed -n 5p $initfile)

#Cut from init file
sdate=$(echo $f1|cut -c 1-10)
edate=$(echo $f2|cut -c 1-10)
txsit=$(echo $tx|cut -c 1-3)
tysit=$(echo $ty|cut -c 1-3)
tzsit=$(echo $tz|cut -c 1-3)

str='\([0-9]\{4\}\),\([0-9]\{2\}\),\([0-9]\{2\}\)' #Look for date with yyyy,mm,dd
str2='  integer::tx_sites = '"$txsit"',ty_sites = '"$tysit"',tz_sites = '"$tzsit"' !For looping through tsites'

#sed -n '/'$str'/p' $initfile
#Search and replace strings in simSettings.txt
sed -i '3s/'$str'/'$sdate'/' $file
sed -i '4s/'$str'/'$edate'/' $file
sed -i '11s/.*/'"$str2"'/' $trackfile 
#sed -i $str3 $trackfile
#f3=$(cut -c 4- $f1)
#echo $f3

echo $str2
echo $sdate
echo $edate
mv $trackfile dummy && mv dummy $trackfile


